version: "3"

services:
  rocketpay-db:
    image: postgres:13.2-alpine
    container_name: rocketpay-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocketpay_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    volumes:
      - rocktetpay-db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  rocktetpay-db-data:
